### ISSUE TITLE
can the rpc port that simplewallet is on be specified?

### ISSUE THREAD

**Issue by Gingeropolous** [ShenNoether/MiniNodo#1]
I see in this command

read -s walletfile
5	/tmp/simplewallet --wallet-file $walletfile --password $password --rpc-bind-port 18082

that the port is specified to 18082, and in your readme its 18082. However, people might already have their servers set up to use 18082 with another simplewallet instance. I couldn't find in the code where the node instance figures out which port to interface with... can this be specified, or is 18082 hardcoded somewhere that I can't find?

**Comment by ShenNoether** [comment]
@Gingeropolous the port is set via the https://github.com/PsychicCat/monero-nodejs so I think you would have to change it with this code: var Wallet = new moneroWallet($HOSTNAME, $PORT); I'll update this to make it variable shortly

**Comment by ShenNoether** [comment]
@Gingeropolous This is sort of fixed in this commit: https://github.com/ShenNoether/MiniNodo/commit/d84eab16761ad0582bc7ad978f8aa49c0f8801ee in that you can update via the settings at top of MiniNodo.js and routes/routes.js . When I have time, I am going to try and more thoroughly clean up and simplify ip / port handling (or pr if you want it sooner).

**Comment by ShenNoether** [comment]
This is now setable with -swp flag.
