### ISSUE TITLE
start command clarification

### ISSUE THREAD

**Issue by Gingeropolous** [ShenNoether/MiniNodo#2]
I'm assuming the start command

node MiniNodo.js 0.0.0.0

means that the mininodo instance is listening on all IPs? So if you wanted to specify a specific IP it would be done here?

**Comment by ShenNoether** [comment]
@Gingeropolous , I just tried the command  node MiniNodo.js 172.31.99.113  which seemed to work. Note that, although the api will work, right now the web-interface will only work by using https://localhost:3000/# in your browser (Once password support is added, I'll remove that block from the api server part of the code, since without the password, you would have an unsecured ip managing your wallet)
